# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               "Jim Hester's blog"
tagline:             ''
description:         ''
home:                http://jimhester.com
url:                 http://jimhester.com
paginate:            5
paginate_path:       "/page:num/"
exclude:             ['posts']
plugins: [jekyll-paginate]

# About/contact
author:
  name:              Jim Hester
  url:               https://twitter.com/jimhester_
  email:             james.f.hester@gmail.com

# Custom vars
version:             1.0.0
